// Objective-C API for talking to github.com/tailscale/tailscale-android/ios/libtailscale Go package.
//   gobind -lang=objc github.com/tailscale/tailscale-android/ios/libtailscale
//
// File is generated by gobind. Do not edit.

#ifndef __Libtailscale_H__
#define __Libtailscale_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LibtailscaleApp;
@class LibtailscaleFilePart;
@class LibtailscaleResponse;
@class LibtailscaleTunnelConfig;
@class LibtailscaleVPNFacade;
@protocol LibtailscaleAppContext;
@class LibtailscaleAppContext;
@protocol LibtailscaleApplication;
@class LibtailscaleApplication;
@protocol LibtailscaleFileParts;
@class LibtailscaleFileParts;
@protocol LibtailscaleInputStream;
@class LibtailscaleInputStream;
@protocol LibtailscaleLocalAPIResponse;
@class LibtailscaleLocalAPIResponse;
@protocol LibtailscaleNotificationCallback;
@class LibtailscaleNotificationCallback;
@protocol LibtailscaleNotificationManager;
@class LibtailscaleNotificationManager;
@protocol LibtailscaleOutputStream;
@class LibtailscaleOutputStream;
@protocol LibtailscaleTunnelConfigCallback;
@class LibtailscaleTunnelConfigCallback;

@protocol LibtailscaleAppContext <NSObject>
- (NSString* _Nonnull)decryptFromPref:(NSString* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
- (BOOL)encryptToPref:(NSString* _Nullable)key value:(NSString* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getDeviceName:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getInstallSource;
- (NSString* _Nonnull)getInterfacesAsJson:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getOSVersion:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getPlatformDNSConfig;
- (NSString* _Nonnull)getStateStoreKeysJSON;
- (BOOL)getSyspolicyBooleanValue:(NSString* _Nullable)key ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getSyspolicyStringArrayJSONValue:(NSString* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getSyspolicyStringValue:(NSString* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)hardwareAttestationKeyCreate:(NSError* _Nullable* _Nullable)error;
- (BOOL)hardwareAttestationKeyLoad:(NSString* _Nullable)keyID error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)hardwareAttestationKeyPublic:(NSString* _Nullable)keyID error:(NSError* _Nullable* _Nullable)error;
- (BOOL)hardwareAttestationKeyRelease:(NSString* _Nullable)keyID error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)hardwareAttestationKeySign:(NSString* _Nullable)keyID data:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
- (BOOL)hardwareAttestationKeySupported;
- (BOOL)isChromeOS:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (void)log:(NSString* _Nullable)tag logLine:(NSString* _Nullable)logLine;
- (BOOL)shouldUseGoogleDNSFallback;
@end

@protocol LibtailscaleApplication <NSObject>
- (id<LibtailscaleLocalAPIResponse> _Nullable)callLocalAPI:(long)timeoutMillis method:(NSString* _Nullable)method endpoint:(NSString* _Nullable)endpoint body:(id<LibtailscaleInputStream> _Nullable)body error:(NSError* _Nullable* _Nullable)error;
- (id<LibtailscaleLocalAPIResponse> _Nullable)callLocalAPIMultipart:(long)timeoutMillis method:(NSString* _Nullable)method endpoint:(NSString* _Nullable)endpoint parts:(id<LibtailscaleFileParts> _Nullable)parts error:(NSError* _Nullable* _Nullable)error;
- (void)notifyPolicyChanged;
- (id<LibtailscaleNotificationManager> _Nullable)watchNotifications:(long)mask cb:(id<LibtailscaleNotificationCallback> _Nullable)cb;
@end

@protocol LibtailscaleFileParts <NSObject>
- (LibtailscaleFilePart* _Nullable)get:(int32_t)p0;
- (int32_t)len;
@end

@protocol LibtailscaleInputStream <NSObject>
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)read:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibtailscaleLocalAPIResponse <NSObject>
- (NSData* _Nullable)bodyBytes:(NSError* _Nullable* _Nullable)error;
- (id<LibtailscaleInputStream> _Nullable)bodyInputStream;
- (long)statusCode;
@end

@protocol LibtailscaleNotificationCallback <NSObject>
- (BOOL)onNotify:(NSData* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibtailscaleNotificationManager <NSObject>
- (void)stop;
@end

@protocol LibtailscaleOutputStream <NSObject>
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)p0 ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

@protocol LibtailscaleTunnelConfigCallback <NSObject>
/**
 * OnTunnelConfigUpdate receives a JSON-encoded TunnelConfig. The
Extension must apply these settings and return nil on success.
 */
- (BOOL)onTunnelConfigUpdate:(NSData* _Nullable)configJSON error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * App is the concrete iOS libtailscale runtime.
 */
@interface LibtailscaleApp : NSObject <goSeqRefInterface, LibtailscaleApplication> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * CallLocalAPI calls the given endpoint on the local API using the given HTTP
method and optionally sending the given body. It returns a Response
representing the result of the call.
 */
- (id<LibtailscaleLocalAPIResponse> _Nullable)callLocalAPI:(long)timeoutMillis method:(NSString* _Nullable)method endpoint:(NSString* _Nullable)endpoint body:(id<LibtailscaleInputStream> _Nullable)body error:(NSError* _Nullable* _Nullable)error;
/**
 * CallLocalAPIMultipart is like CallLocalAPI, but instead of uploading a
generic body, it uploads a multipart/form-encoded body consisting of the
supplied parts.
 */
- (id<LibtailscaleLocalAPIResponse> _Nullable)callLocalAPIMultipart:(long)timeoutMillis method:(NSString* _Nullable)method endpoint:(NSString* _Nullable)endpoint parts:(id<LibtailscaleFileParts> _Nullable)parts error:(NSError* _Nullable* _Nullable)error;
// skipped method App.EditPrefs with unsupported parameter or return types

/**
 * NotifyPolicyChanged notifies the backend about a changed MDM policy.
 */
- (void)notifyPolicyChanged;
- (id<LibtailscaleNotificationManager> _Nullable)watchNotifications:(long)mask cb:(id<LibtailscaleNotificationCallback> _Nullable)cb;
@end

/**
 * FilePart is a multipart file that can be submitted via CallLocalAPIMultipart.
 */
@interface LibtailscaleFilePart : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t contentLength;
@property (nonatomic) NSString* _Nonnull filename;
@property (nonatomic) id<LibtailscaleInputStream> _Nullable body;
@property (nonatomic) NSString* _Nonnull contentType;
@end

/**
 * Response represents the result of processing a localAPI request.
 */
@interface LibtailscaleResponse : NSObject <goSeqRefInterface, LibtailscaleLocalAPIResponse> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped method Response.Body with unsupported parameter or return types

- (NSData* _Nullable)bodyBytes:(NSError* _Nullable* _Nullable)error;
- (id<LibtailscaleInputStream> _Nullable)bodyInputStream;
- (void)flush;
// skipped method Response.Header with unsupported parameter or return types

- (long)statusCode;
- (BOOL)write:(NSData* _Nullable)data ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (void)writeHeader:(long)statusCode;
@end

/**
 * TunnelConfig is the JSON-serializable tunnel configuration pushed to Swift.
It contains everything NEPacketTunnelProvider needs to call
setTunnelNetworkSettings.
 */
@interface LibtailscaleTunnelConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TunnelConfig.LocalAddresses with unsupported type: []string

// skipped field TunnelConfig.Routes with unsupported type: []string

// skipped field TunnelConfig.ExcludeRoutes with unsupported type: []string

// skipped field TunnelConfig.DNSServers with unsupported type: []string

// skipped field TunnelConfig.DNSDomains with unsupported type: []string

/**
 * Tunnel
 */
@property (nonatomic) long mtu;
@end

/**
 * VPNFacade implements both router.Router and dns.OSConfigurator.
When ReconfigureVPN is called by the backend, SetBoth gets called.
 */
@interface LibtailscaleVPNFacade : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field VPNFacade.SetBoth with unsupported type: func(rcfg *tailscale.com/wgengine/router.Config, dcfg *tailscale.com/net/dns.OSConfig) error

// skipped field VPNFacade.GetBaseConfigFunc with unsupported type: func() (tailscale.com/net/dns.OSConfig, error)

// skipped field VPNFacade.InitialMTU with unsupported type: uint32

- (BOOL)close:(NSError* _Nullable* _Nullable)error;
// skipped method VPNFacade.GetBaseConfig with unsupported parameter or return types

- (BOOL)reconfigureVPN:(NSError* _Nullable* _Nullable)error;
// skipped method VPNFacade.Set with unsupported parameter or return types

// skipped method VPNFacade.SetDNS with unsupported parameter or return types

- (BOOL)supportsSplitDNS;
- (BOOL)up:(NSError* _Nullable* _Nullable)error;
// skipped method VPNFacade.UpdateMagicsockPort with unsupported parameter or return types

@end

/**
 * SetTunnelConfigCallback registers a callback that will be invoked whenever
the Go backend updates the VPN tunnel configuration (routes, DNS, etc.).
Must be called after Start() and before the backend sends its first config.
 */
FOUNDATION_EXPORT void LibtailscaleSetTunnelConfigCallback(id<LibtailscaleApplication> _Nullable app, id<LibtailscaleTunnelConfigCallback> _Nullable cb);

/**
 * Start starts the iOS libtailscale runtime.
 */
FOUNDATION_EXPORT id<LibtailscaleApplication> _Nullable LibtailscaleStart(NSString* _Nullable dataDir, NSString* _Nullable directFileRoot, BOOL hwAttestationPref, id<LibtailscaleAppContext> _Nullable appCtx);

@class LibtailscaleAppContext;

@class LibtailscaleApplication;

@class LibtailscaleFileParts;

@class LibtailscaleInputStream;

@class LibtailscaleLocalAPIResponse;

@class LibtailscaleNotificationCallback;

@class LibtailscaleNotificationManager;

@class LibtailscaleOutputStream;

@class LibtailscaleTunnelConfigCallback;

/**
 * AppContext provides the platform hooks implemented on the Swift side.
 */
@interface LibtailscaleAppContext : NSObject <goSeqRefInterface, LibtailscaleAppContext> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)decryptFromPref:(NSString* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
- (BOOL)encryptToPref:(NSString* _Nullable)key value:(NSString* _Nullable)value error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getDeviceName:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getInstallSource;
- (NSString* _Nonnull)getInterfacesAsJson:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getOSVersion:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getPlatformDNSConfig;
- (NSString* _Nonnull)getStateStoreKeysJSON;
- (BOOL)getSyspolicyBooleanValue:(NSString* _Nullable)key ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getSyspolicyStringArrayJSONValue:(NSString* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getSyspolicyStringValue:(NSString* _Nullable)key error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)hardwareAttestationKeyCreate:(NSError* _Nullable* _Nullable)error;
- (BOOL)hardwareAttestationKeyLoad:(NSString* _Nullable)keyID error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)hardwareAttestationKeyPublic:(NSString* _Nullable)keyID error:(NSError* _Nullable* _Nullable)error;
- (BOOL)hardwareAttestationKeyRelease:(NSString* _Nullable)keyID error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)hardwareAttestationKeySign:(NSString* _Nullable)keyID data:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
- (BOOL)hardwareAttestationKeySupported;
- (BOOL)isChromeOS:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (void)log:(NSString* _Nullable)tag logLine:(NSString* _Nullable)logLine;
- (BOOL)shouldUseGoogleDNSFallback;
@end

/**
 * Application encapsulates the running iOS libtailscale application.
 */
@interface LibtailscaleApplication : NSObject <goSeqRefInterface, LibtailscaleApplication> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (id<LibtailscaleLocalAPIResponse> _Nullable)callLocalAPI:(long)timeoutMillis method:(NSString* _Nullable)method endpoint:(NSString* _Nullable)endpoint body:(id<LibtailscaleInputStream> _Nullable)body error:(NSError* _Nullable* _Nullable)error;
- (id<LibtailscaleLocalAPIResponse> _Nullable)callLocalAPIMultipart:(long)timeoutMillis method:(NSString* _Nullable)method endpoint:(NSString* _Nullable)endpoint parts:(id<LibtailscaleFileParts> _Nullable)parts error:(NSError* _Nullable* _Nullable)error;
- (void)notifyPolicyChanged;
- (id<LibtailscaleNotificationManager> _Nullable)watchNotifications:(long)mask cb:(id<LibtailscaleNotificationCallback> _Nullable)cb;
@end

/**
 * FileParts is an array of multiple FileParts.
 */
@interface LibtailscaleFileParts : NSObject <goSeqRefInterface, LibtailscaleFileParts> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (LibtailscaleFilePart* _Nullable)get:(int32_t)p0;
- (int32_t)len;
@end

/**
 * InputStream provides an adapter between Swift streams and Go readers.
 */
@interface LibtailscaleInputStream : NSObject <goSeqRefInterface, LibtailscaleInputStream> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)read:(NSError* _Nullable* _Nullable)error;
@end

/**
 * LocalAPIResponse is a response to a localapi call.
 */
@interface LibtailscaleLocalAPIResponse : NSObject <goSeqRefInterface, LibtailscaleLocalAPIResponse> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSData* _Nullable)bodyBytes:(NSError* _Nullable* _Nullable)error;
- (id<LibtailscaleInputStream> _Nullable)bodyInputStream;
- (long)statusCode;
@end

/**
 * NotificationCallback receives ipn.Notify messages serialized as JSON.
 */
@interface LibtailscaleNotificationCallback : NSObject <goSeqRefInterface, LibtailscaleNotificationCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)onNotify:(NSData* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NotificationManager lets callers stop receiving notifications.
 */
@interface LibtailscaleNotificationManager : NSObject <goSeqRefInterface, LibtailscaleNotificationManager> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)stop;
@end

/**
 * OutputStream provides an adapter between Swift streams and Go writers.
 */
@interface LibtailscaleOutputStream : NSObject <goSeqRefInterface, LibtailscaleOutputStream> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)p0 ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * TunnelConfigCallback receives tunnel configuration updates from the Go
backend (router.Config + dns.OSConfig) serialized as JSON. Swift implements
this to call NEPacketTunnelProvider.setTunnelNetworkSettings.
 */
@interface LibtailscaleTunnelConfigCallback : NSObject <goSeqRefInterface, LibtailscaleTunnelConfigCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * OnTunnelConfigUpdate receives a JSON-encoded TunnelConfig. The
Extension must apply these settings and return nil on success.
 */
- (BOOL)onTunnelConfigUpdate:(NSData* _Nullable)configJSON error:(NSError* _Nullable* _Nullable)error;
@end

#endif
