
// Objective-C API for talking to the following Go packages
//
//	github.com/tailscale/tailscale-android/ios/libtailscale
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libtailscale_FRAMEWORK_H__
#define __Libtailscale_FRAMEWORK_H__

#include "Libtailscale.objc.h"
#include "Universe.objc.h"

#endif
